### PR TITLE
Add Wandalen/wretry.action@v3 with subactions

### PR DESCRIPTION
**Pull request by Vampire**
Upstream PR: https://github.com/Wandalen/wretry.action/pull/167

### CODE REVIEW

**Review by krzema12 — APPROVED** [review]

**Comment by Vampire** [comment]
Upstream was merged too. :-)
Do we need to do something here, for example to not handle updates?

**Comment by krzema12** [comment]
We need the action to get a new release with the typings, then we just remove the typings from the catalog and that's all!

**Comment by Vampire** [comment]
But that's a breaking change. 
If we have typings for v1 and the action adds typings for v2, then if we remove the typing from the catalog all v1 usage is broken. 

Or if someone uses v1.0.1 with the v1 typings from the catalog and the action adds the typings in v1.0.2, then the 1.0.1 usage will also be broken when removing from the catalog.

**Comment by krzema12** [comment]
If Wandalen adds a new major version (v2), then you're right, we should keep the typings as we're the only source of typings for your exemplary v1. But if they just update the existing major version tag/branch with the typings, I think we're safe.

**Comment by Vampire** [comment]
> But if they just update the existing major version tag/branch with the typings, I think we're safe.

As I said, not if anyone uses a version more concrete than just major:

```plain
?? Requesting tecolicom/actions-use-homebrew-tools@v1.2
  ... from https://raw.githubusercontent.com/tecolicom/actions-use-homebrew-tools/v1.2/action.yml
  ... types from https://raw.githubusercontent.com/tecolicom/actions-use-homebrew-tools/v1.2/action-types.yml
  ... types from https://raw.githubusercontent.com/tecolicom/actions-use-homebrew-tools/v1.2/action-types.yaml
  ... types from https://raw.githubusercontent.com/typesafegithub/github-actions-typing-catalog/main/typings/tecolicom/actions-use-homebrew-tools/v1/action-types.yml
?? Requesting tecolicom/actions-use-homebrew-tools@v1.2
?? Requesting tecolicom/actions-use-homebrew-tools@v1.2
?? Requesting tecolicom/actions-use-homebrew-tools@v1.2
?? Requesting tecolicom/actions-use-homebrew-tools@v1.2
?? Requesting tecolicom/actions-use-homebrew-tools@v1.2

?? Requesting tecolicom/actions-use-homebrew-tools@v1.3
  ... from https://raw.githubusercontent.com/tecolicom/actions-use-homebrew-tools/v1.3/action.yml
  ... types from https://raw.githubusercontent.com/tecolicom/actions-use-homebrew-tools/v1.3/action-types.yml
?? Requesting tecolicom/actions-use-homebrew-tools@v1.3
?? Requesting tecolicom/actions-use-homebrew-tools@v1.3
?? Requesting tecolicom/actions-use-homebrew-tools@v1.3
?? Requesting tecolicom/actions-use-homebrew-tools@v1.3
?? Requesting tecolicom/actions-use-homebrew-tools@v1.3
```

When you request 1.3, it uses the upstream typings.
When you request 1.2, it uses the catalog v1 typings.

**Pull request merged**
