### PR TITLE
Add tecolicom/actions-use-homebrew-tools@v1

### PR DESCRIPTION
**Pull request by Vampire**
Upstream PR: https://github.com/tecolicom/actions-use-homebrew-tools/pull/5

### CODE REVIEW

**Review by krzema12 — APPROVED** [review]

**Comment by krzema12** [comment]
@Vampire fun fact: the action's manifest contains some type information: https://github.com/tecolicom/actions-use-homebrew-tools/blob/8a51b98f7de2d879555b31b92d6d640918c8538b/action.yml#L9

**Comment by Vampire** [comment]
Yes, I've seen that and assume it is just there as it makes sense to have it there, even if not officially defined.

**Comment by Vampire** [comment]
upstream pr was merged and released as v1.3 and v1 :-)

**Comment by krzema12** [comment]
https://github.com/typesafegithub/github-actions-typing-catalog/pull/28

**Pull request merged**
